name: .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest  # .NET Framework is typically used on Windows

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.7.2'  # Replace with the version you need
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Test
      run: echo "No tests specified for .NET Framework"

