name: .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest  # Use a Windows runner for .NET Framework

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework
      run: |
        choco install dotnet-framework-sdk -y --version=4.7.2
        dotnet --version
    - name: Restore dependencies
      run: nuget restore
    - name: Setup Visual Studio Build Tools
      uses: actions/setup-vs-build-tools@v2
      with:
        visualstudio-version: '2019'
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Test
      run: echo "No tests specified for .NET Framework"
