name: .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest  # Use a Windows runner for .NET Framework

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: |
        msbuild /p:Configuration=Release Devops&Security-CaseStudy4.sln

    - name: Test
      run: echo "No tests specified for .NET Framework"
